name: test

on:
  push:
    branches: [master, ci_cd]
  pull_request:
    branches: [master, ci_cd]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wemake-python-styleguide
          pip install flake8-html
          pip install mypy

      - name: Lint with wemake-python-styleguide
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --format=html --htmldir=flake-report
          flake8 . --count --exit-zero --exclude __init__.py --max-complexity 6 --max-line-length 120 --statistics --format=html --htmldir=flake-report

      - name: Upload linter HTML report
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: Linter HTML report
          path: flake-report
          if-no-files-found: ignore

      - name: Check with Mypy
        run: |
          mypy . --ignore-missing-imports --disallow-untyped-decorators

      - name: Send telegram message on pull-request (fail)
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.repository }} repository.
            ${{ github.actor }} created PR:
            Pipeline ${{github.sha}} python version ${{ matrix.python-version }} finished with error!

      - name: Send telegram message on pull-request (successful)
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.repository }} repository.
            ${{ github.actor }} created PR:
            Pipeline for ${{github.sha}} python version ${{ matrix.python-version }} finished successfully!
